apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJlbmRhZXRoaWEuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlkzSmxaRHBVWVcxbGNqRTFNdz09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
